# dataset:
#   name: "SYNTHETIC_CIFAR100_1M"
#   partial: true
#   subset_idxs: ["train"]
#   original_scores_file: "/nfs/homedirs/dhp/unsupervised-data-pruning/scores/SYNTHETIC_CIFAR100_1M_dynamic_uncertainty_train_2.json"
#   subset_scores_file: "/nfs/homedirs/dhp/unsupervised-data-pruning/scores/SYNTHETIC_CIFAR100_1M_dynamic_uncertainty_train_2.json"

# models:
#   names: ["resnet50"]
#   resnet50:
#     path: "/nfs/homedirs/dhp/unsupervised-data-pruning/models/SYNTHETIC_CIFAR100_1M_ResNet50.pt"

# hyperparams:
#   k_values: [10]
#   num_seeds: [1000]
#   distance: "euclidean"
#   lr: 0.01
#   epochs: 5000
#   gnn:
#     type: "gcn"  # Options: "gcn", "gat"
#     hidden_layers: [512, 256, 128]

# wandb:
#   project: "GNN extrapolate"

# output:
#   results_file: "/nfs/homedirs/dhp/unsupervised-data-pruning/data/gnn_extrapolation.csv"

# dataset:
#   name: "CIFAR10"
#   num_classes: 10
#   image_size: 32
#   partial: false
#   subset_idxs: ["train"]
#   original_scores_file: "/nfs/homedirs/dhp/unsupervised-data-pruning/scores/prune/CIFAR10_dynamic_uncertainty_0.json"
#   subset_scores_file: "/nfs/homedirs/dhp/unsupervised-data-pruning/scores/extrapolation/subset/CIFAR10_dynamic_uncertainty_0.json"
  
# models:
#   names: ["resnet50-self-trained"]
#   resnet50:
#     path: "/nfs/homedirs/dhp/unsupervised-data-pruning/models/CIFAR10/subset/dynamic_uncertainty.pth"

# hyperparams:
#   k_values: [10]
#   distance: "euclidean"
#   lr: 0.01
#   epochs: 2000
#   gnn:
#     type: "gcn"  # Options: "gcn", "gat"
#     hidden_layers: [512, 256, 128]

# wandb:
#   project: "GNN extrapolate"

# output:
#   extrapolated_scores_dir: "/nfs/homedirs/dhp/unsupervised-data-pruning/scores/extrapolation/extrapolated"
#   results_file: "/nfs/homedirs/dhp/unsupervised-data-pruning/data/gnn_extrapolation_cifar10.csv"

# checkpoints:
#   read_embeddings: true
#   save_embeddings: true
#   embeddings_file: "/nfs/homedirs/dhp/unsupervised-data-pruning/savedir/embeddings/CIFAR10/embeddings_dict.pth"
#   read_knn: true
#   save_knn: true
#   knn_file: "/nfs/homedirs/dhp/unsupervised-data-pruning/savedir/knn/CIFAR10/knn.pth"


dataset:
  name: "PLACES_365"
  num_classes: 365
  image_size: 64
  partial: false
  subset_idxs: ["train"]
  original_scores_file: "/nfs/homedirs/dhp/unsupervised-data-pruning/scores/prune/PLACES_365_dynamic_uncertainty_0.json"
  subset_scores_file: "/nfs/homedirs/dhp/unsupervised-data-pruning/scores/extrapolation/subset/PLACES_365_dynamic_uncertainty_0.json"
  
models:
  names: ["resnet50-self-trained"]
  resnet50:
    path: "/nfs/homedirs/dhp/unsupervised-data-pruning/models/places365/subset_data/dynamic_uncertainty.pth"

hyperparams:
  k_values: [10, 20, 50]
  distance: "euclidean"
  lr: 0.01
  epochs: 5000
  gnn:
    type: "gcn"  # Options: "gcn", "gat"
    hidden_layers: [512, 256, 128]

wandb:
  project: "GNN extrapolate"

output:
  extrapolated_scores_dir: "/nfs/homedirs/dhp/unsupervised-data-pruning/scores/extrapolation/extrapolated"
  results_file: "/nfs/homedirs/dhp/unsupervised-data-pruning/data/gnn_extrapolation_cifar10.csv"

checkpoints:
  read_embeddings: true
  save_embeddings: true
  embeddings_file: "/nfs/homedirs/dhp/unsupervised-data-pruning/savedir/embeddings/places365/embeddings_dict.pth"
  read_knn: true
  save_knn: true
  knn_file: "/nfs/homedirs/dhp/unsupervised-data-pruning/savedir/knn/places365/knn.pth"
