CIFAR10:
  dataset:
    name: "CIFAR10"
    num_classes: 10
    image_size: 32

  scores:
    type: "du"
    original_scores_file: "/nfs/homedirs/dhp/unsupervised-data-pruning/scores/prune/CIFAR10_dynamic_uncertainty_0_5_12.json"
    subset_scores_file: "/nfs/homedirs/dhp/unsupervised-data-pruning/scores/extrapolation/subset/CIFAR10_dynamic_uncertainty_0_10000_5_14.json"
    normalize_scores: false
    
  models:
    names: ["resnet18-self-trained"]
    resnet50:
      path: "/nfs/homedirs/dhp/unsupervised-data-pruning/models/CIFAR10/subset_data/dynamic_uncertainty_10000.pth"

  hyperparams:
    k_values: [10, 20, 50, 100]
    distance: "euclidean"

  output:
    knn_dict_path: "/nfs/homedirs/dhp/unsupervised-data-pruning/scores/extrapolation/extrapolated/knn"

  checkpoints:
    read_embeddings: false
    save_embeddings: false
    embeddings_file: "/nfs/homedirs/dhp/unsupervised-data-pruning/savedir/embeddings/CIFAR10/embeddings_dict.pth"

SYNTHETIC_CIFAR100_1M:
  dataset:
    name: "SYNTHETIC_CIFAR100_1M"
    num_classes: 100
    image_size: 32

  scores:
    type: "du"
    original_scores_file: "/nfs/homedirs/dhp/unsupervised-data-pruning/scores/prune/SYNTHETIC_CIFAR100_1M_dynamic_uncertainty_0.json"
    subset_scores_file: "/nfs/homedirs/dhp/unsupervised-data-pruning/scores/extrapolation/subset/SYNTHETIC_CIFAR100_1M_dynamic_uncertainty_0.json"
    normalize_scores: false

  models:
    names: ["resnet50-self-trained"]
    resnet50:
      path: "/nfs/homedirs/dhp/unsupervised-data-pruning/models/SYNTHETIC_CIFAR100_1M/subset_data/dynamic_uncertainty.pth"

  hyperparams:
    k_values: [10, 20, 50]
    distance: "euclidean"

  output:
    knn_dict_path: "/nfs/homedirs/dhp/unsupervised-data-pruning/scores/extrapolation/extrapolated/knn"

  checkpoints:
    read_embeddings: false
    save_embeddings: false
    embeddings_file: "/nfs/homedirs/dhp/unsupervised-data-pruning/savedir/embeddings/SYNTHETIC_CIFAR100_1M/embeddings_dict.pth"


PLACES_365:
  dataset:
    name: "PLACES_365"
    num_classes: 365
    image_size: 64

  scores:
    type: "DU"
    original_scores_file: "/nfs/homedirs/dhp/unsupervised-data-pruning/scores/prune/PLACES_365_dynamic_uncertainty_0.json"
    subset_scores_file: "/nfs/homedirs/dhp/unsupervised-data-pruning/scores/extrapolation/subset/PLACES_365_last_tdds_0_450000_3_28.json"
    normalize_scores: false
    
  models:
    names: ["resnet50-self-trained"]
    resnet50:
      path: "/nfs/homedirs/dhp/unsupervised-data-pruning/models/places365/subset_data/dynamic_uncertainty.pth"

  hyperparams:
    k_values: [50]
    distance: "euclidean"

  output:
    knn_dict_path: "/nfs/homedirs/dhp/unsupervised-data-pruning/scores/extrapolation/extrapolated/knn"

  checkpoints:
    read_embeddings: false
    save_embeddings: false
    embeddings_file: "/nfs/homedirs/dhp/unsupervised-data-pruning/savedir/embeddings/places365/embeddings_dict.pth"

IMAGENET:
  dataset:
    name: "IMAGENET"
    num_classes: 1000
    image_size: 64

  scores:
    type: "du"
    original_scores_file: "/nfs/homedirs/dhp/unsupervised-data-pruning/scores/prune/IMAGENET_dynamic_uncertainty_0_4_20.json"
    subset_scores_file: "/nfs/homedirs/dhp/unsupervised-data-pruning/scores/extrapolation/subset/IMAGENET_dynamic_uncertainty_0_256234_4_19.json"
    normalize_scores: false
    
  models:
    names: ["resnet18-self-trained"]
    resnet50:
      path: "/nfs/homedirs/dhp/unsupervised-data-pruning/models/imagenet/subset_data/dynamic_uncertainty_256234.pth"

  hyperparams:
    k_values: [10, 20, 50]
    distance: "euclidean"

  output:
    knn_dict_path: "/nfs/homedirs/dhp/unsupervised-data-pruning/scores/extrapolation/extrapolated/knn_"

  checkpoints:
    read_embeddings: false
    save_embeddings: false
    embeddings_file: "/nfs/homedirs/dhp/unsupervised-data-pruning/savedir/embeddings/imagenet/embeddings_dict.pth"
