CIFAR10:
  dataset:
    name: "CIFAR10"
    root_dir: "data"
    num_classes: 10
    image_size: 32

  scores:
    type: "unsupervised-DU"
    original_scores_file: "/nfs/homedirs/dhp/unsupervised-data-pruning/scores/prune/CIFAR10_unsupervised_dynamic_uncertainty_4_6.json"
    subset_scores_file: "/nfs/homedirs/dhp/unsupervised-data-pruning/scores/extrapolation/subset/CIFAR10_unsupervised_dynamic_uncertainty_5_11.json"
    normalize_scores: false
    
  models:
    names: ["dinov2"]
    path: "/nfs/homedirs/dhp/turtle/data/checkpoints/dinov2"
    torch_hub: "facebookresearch/dinov2"
    version: "dinov2_vitg14"

    # names: ["resnet50-self-trained"]
    # resnet50:
    #   path: "/nfs/homedirs/dhp/unsupervised-data-pruning/models/CIFAR10/subset_data/dynamic_uncertainty.pth"

  training:
    seed: 42
    batch_size: 10000
    batch_size_repr: 256
    gamma: 10.0
    T: 6000
    inner_lr: 0.001
    outer_lr: 0.001
    warm_start: false
    M: 10
    num_epochs: 50
    lr: 0.001
    weight_decay: 0.001


  hyperparams:
    k_values: [10, 20, 50]
    distance: "euclidean"


  output:
    results_path: "/nfs/homedirs/dhp/unsupervised-data-pruning/data/knn_extrapolation_cifar10.csv"
    knn_dict_path: "/nfs/homedirs/dhp/unsupervised-data-pruning/scores/extrapolation/extrapolated/knn"

  checkpoints:
    read_embeddings: false
    save_embeddings: false
    embeddings_file: "/nfs/homedirs/dhp/unsupervised-data-pruning/savedir/embeddings/CIFAR10/embeddings_dict.pth"
