CIFAR10:
  dataset:
    name: "CIFAR10"
    num_classes: 10
    image_size: 32

  scores:
    type: "tdds"
    original_scores_file: "/nfs/homedirs/dhp/unsupervised-data-pruning/scores/prune/CIFAR10_tdds_0.json"
    subset_scores_file: "/nfs/homedirs/dhp/unsupervised-data-pruning/scores/extrapolation/subset/CIFAR10_tdds_0.json"
    
  models:
    names: ["resnet50-self-trained"]
    resnet50:
      path: "/nfs/homedirs/dhp/unsupervised-data-pruning/models/CIFAR10/subset_data/tdds.pth"

  hyperparams:
    k_values: [10, 20, 50, 100]
    distance: "euclidean"

  output:
    results_path: /nfs/homedirs/dhp/unsupervised-data-pruning/data/knn_extrapolation_CIFAR10.csv
    knn_dict_path: /nfs/homedirs/dhp/unsupervised-data-pruning/scores/extrapolation/extrapolated/knn_

  checkpoints:
    read_embeddings: false
    save_embeddings: false
    embeddings_file: "/nfs/homedirs/dhp/unsupervised-data-pruning/savedir/embeddings/CIFAR10/embeddings_dict.pth"

SYNTHETIC_CIFAR100_1M:
  dataset:
    name: "SYNTHETIC_CIFAR100_1M"
    num_classes: 100
    image_size: 32

  scores:
    type: "DU"
    original_scores_file: "/nfs/homedirs/dhp/unsupervised-data-pruning/scores/prune/SYNTHETIC_CIFAR100_1M_dynamic_uncertainty_0.json"
    subset_scores_file: "/nfs/homedirs/dhp/unsupervised-data-pruning/scores/extrapolation/subset/SYNTHETIC_CIFAR100_1M_dynamic_uncertainty_0_10000.json"

  models:
    names: ["resnet50-self-trained"]
    resnet50:
      path: "/nfs/homedirs/dhp/unsupervised-data-pruning/models/SYNTHETIC_CIFAR100_1M/subset_data/dynamic_uncertainty_10000.pth"

  hyperparams:
    k_values: [50]
    distance: "euclidean"

  output:
    results_path: /nfs/homedirs/dhp/unsupervised-data-pruning/data/knn_extrapolation_SYNTHETIC_CIFAR100_1M.csv
    knn_dict_path: /nfs/homedirs/dhp/unsupervised-data-pruning/scores/extrapolation/extrapolated/knn_

  checkpoints:
    read_embeddings: false
    save_embeddings: false
    embeddings_file: "/nfs/homedirs/dhp/unsupervised-data-pruning/savedir/embeddings/SYNTHETIC_CIFAR100_1M/embeddings_dict.pth"


PLACES_365:
  dataset:
    name: "PLACES_365"
    num_classes: 365
    image_size: 64

  scores:
    type: "DU"
    original_scores_file: "/nfs/homedirs/dhp/unsupervised-data-pruning/scores/prune/PLACES_365_dynamic_uncertainty_0.json"
    subset_scores_file: "/nfs/homedirs/dhp/unsupervised-data-pruning/scores/extrapolation/subset/PLACES_365_dynamic_uncertainty_0_180000.json"
    
  models:
    names: ["resnet50-self-trained"]
    resnet50:
      path: "/nfs/homedirs/dhp/unsupervised-data-pruning/models/places365/subset_data/dynamic_uncertainty_180000.pth"

  hyperparams:
    k_values: [50]
    distance: "euclidean"

  output:
    results_path: /nfs/homedirs/dhp/unsupervised-data-pruning/data/knn_extrapolation_places_365_new.csv
    knn_dict_path: /nfs/homedirs/dhp/unsupervised-data-pruning/scores/extrapolation/extrapolated/knn_

  checkpoints:
    read_embeddings: false
    save_embeddings: false
    embeddings_file: "/nfs/homedirs/dhp/unsupervised-data-pruning/savedir/embeddings/places365/embeddings_dict.pth"