dataset:
  name: "CIFAR10"
  num_classes: 10
  image_size: 32
  partial: false
  subset_idxs: ["train"]
  original_scores_file: "/nfs/homedirs/dhp/unsupervised-data-pruning/scores/prune/CIFAR10_dynamic_uncertainty_0.json"
  subset_scores_file: "/nfs/homedirs/dhp/unsupervised-data-pruning/scores/extrapolation/subset/CIFAR10_dynamic_uncertainty_0.json"
  
models:
  names: ["resnet50-self-trained"]
  resnet50:
    path: "/nfs/homedirs/dhp/unsupervised-data-pruning/models/CIFAR10/subset/dynamic_uncertainty.pth"

hyperparams:
  k_values: [10]
  distance: "euclidean"

output:
  results_path: /nfs/homedirs/dhp/unsupervised-data-pruning/data/knn_extrapolation_CIFAR10.csv
  knn_dict_path: /nfs/homedirs/dhp/unsupervised-data-pruning/scores/extrapolation/extrapolated/knn_extrapolation

checkpoints:
  read_embeddings: true
  save_embeddings: false
  embeddings_file: "/nfs/homedirs/dhp/unsupervised-data-pruning/savedir/embeddings/CIFAR10/embeddings_dict.pth"

# dataset:
#   name: "PLACES_365"
#   num_classes: 365
#   image_size: 64
#   partial: false
#   subset_idxs: ["train"]
#   original_scores_file: "/nfs/homedirs/dhp/unsupervised-data-pruning/scores/prune/PLACES_365_dynamic_uncertainty_0.json"
#   subset_scores_file: "/nfs/homedirs/dhp/unsupervised-data-pruning/scores/extrapolation/subset/PLACES_365_dynamic_uncertainty_0.json"
  
# models:
#   names: ["resnet50-self-trained"]
#   resnet50:
#     path: "/nfs/homedirs/dhp/unsupervised-data-pruning/models/places365/subset_data/dynamic_uncertainty.pth"

# hyperparams:
#   k_values: [10, 20, 50, 100]
#   distance: "euclidean"

# output:
#   results_path: /nfs/homedirs/dhp/unsupervised-data-pruning/data/knn_extrapolation_places_365.csv
#   knn_dict_path: /nfs/homedirs/dhp/unsupervised-data-pruning/scores/extrapolation/extrapolated/knn_extrapolation

# checkpoints:
#   read_embeddings: true
#   save_embeddings: false
#   embeddings_file: "/nfs/homedirs/dhp/unsupervised-data-pruning/savedir/embeddings/places365/embeddings_dict.pth"