# for SYNTHETIC_CIFAR100_1M dataset
# experiment:
#   num_iterations: 1

# dataset:
#   name: "SYNTHETIC_CIFAR100_1M"
#   num_classes: 100
#   partial: true
#   subset: ["train"]

# model:
#   name: "ResNet50"

# training:
#   batch_size: 256
#   num_epochs: 4
#   lr: 0.001
#   weight_decay: 0.001

# uncertainty:
#   window: 2

# pruning:
#   percentages: [0.1, 0.2, 0.5]

# logging:
#   log_interval: 1000

# paths:
#   scores: "/nfs/homedirs/dhp/unsupervised-data-pruning/scores"

# for PLACES365 dataset
experiment:
  num_iterations: 1

dataset:
  name: "PLACES_365"
  num_classes: 365
  partial: false
  image_size: 64
  subset: []
  for_extrapolation:
    value: true
    subset_size: 450000

model:
  name: "ResNet50"

training:
  batch_size: 128
  num_epochs: 50
  lr: 0.001
  weight_decay: 0.001

uncertainty:
  window: 10

pruning:
  prune: false
  percentages: [0.1, 0.2, 0.5]

logging:
  log_interval: 15000

paths:
  scores: "/nfs/homedirs/dhp/unsupervised-data-pruning/scores/extrapolation/subset_scores"
  models: "/nfs/homedirs/dhp/unsupervised-data-pruning/models/places365"
