CIFAR10:
  experiment:
    num_iterations: 2

  dataset:
    name: "CIFAR10"
    num_classes: 10
    image_size: 32
    for_extrapolation:
      value: true
      # value: false
      subset_size: 10000

  model:
    name: "ResNet18"

  pruning:
    prune: false
    # prune: true
    percentages: [0.95, 0.9, 0.8, 0.5, 0.2, 0.1]

  training:
    batch_size: 256
    num_epochs: 50
    lr: 0.001
    weight_decay: 0.001

  uncertainty:
    window: 10

  logging:
    log_interval: 15000

  paths:
    # scores: "/nfs/homedirs/dhp/unsupervised-data-pruning/scores/prune"
    scores: "/nfs/homedirs/dhp/unsupervised-data-pruning/scores/extrapolation/subset"
    # models: "/nfs/homedirs/dhp/unsupervised-data-pruning/models/CIFAR10/full_data"
    models: "/nfs/homedirs/dhp/unsupervised-data-pruning/models/CIFAR10/subset_data"


SYNTHETIC_CIFAR100_1M:
  experiment:
    num_iterations: 1

  dataset:
    name: "SYNTHETIC_CIFAR100_1M"
    num_classes: 100
    image_size: 32
    for_extrapolation:
      value: true
      subset_size: 300000

  model:
    name: "ResNet50"

  training:
    batch_size: 256
    num_epochs: 50
    lr: 0.001
    weight_decay: 0.001

  uncertainty:
    window: 10

  pruning:
    prune: false
    percentages: [0.1, 0.2, 0.5]

  logging:
    log_interval: 15000

  paths:
    scores: "/nfs/homedirs/dhp/unsupervised-data-pruning/scores/extrapolation/subset"
    models: "/nfs/homedirs/dhp/unsupervised-data-pruning/models/SYNTHETIC_CIFAR100_1M/subset_data"

PLACES_365:
  experiment:
    num_iterations: 1

  dataset:
    name: "PLACES_365"
    num_classes: 365
    image_size: 64
    for_extrapolation:
      value: true
      subset_size: 450000

  model:
    name: "ResNet50"

  training:
    batch_size: 128
    num_epochs: 50
    lr: 0.001
    weight_decay: 0.001

  uncertainty:
    window: 10

  pruning:
    prune: false
    percentages: [0.1, 0.2, 0.5]

  logging:
    log_interval: 15000

  paths:
    scores: "/nfs/homedirs/dhp/unsupervised-data-pruning/scores/extrapolation/subset"
    models: "/nfs/homedirs/dhp/unsupervised-data-pruning/models/places365/subset_data"

IMAGENET:
  experiment:
    num_iterations: 1

  dataset:
    name: "IMAGENET"
    num_classes: 1000
    image_size: 64
    for_extrapolation:
      value: true
      # subset_size: 256234
      subset_size: 128117

  model:
    name: "ResNet18"

  training:
    batch_size: 256
    num_epochs: 90
    lr: 0.001
    weight_decay: 0.0001

  uncertainty:
    window: 10

  pruning:
    prune: false
    percentages: [0.1, 0.2, 0.5, 0.8, 0.9, 0.95]

  logging:
    log_interval: 45000

  paths:
    scores: "/nfs/homedirs/dhp/unsupervised-data-pruning/scores/extrapolation/subset"
    models: "/nfs/homedirs/dhp/unsupervised-data-pruning/models/imagenet/subset_data"
