# for SYNTHETIC_CIFAR100_1M dataset
CIFAR10:
  experiment:
    num_iterations: 1

  dataset:
    name: "CIFAR10"
    num_classes: 10
    image_size: 32
    for_extrapolation:
      value: false
      subset_size: 20000

  model:
    name: "ResNet50"

  pruning:
    prune: false
    percentages: [0.5, 0.2, 0.1]

  training:
    batch_size: 256
    num_epochs: 50
    lr: 0.001
    weight_decay: 0.001

  uncertainty:
    window: 10

  logging:
    log_interval: 15000

  paths:
    scores: "/nfs/homedirs/dhp/unsupervised-data-pruning/scores/prune"
    models: "/nfs/homedirs/dhp/unsupervised-data-pruning/models/CIFAR10/full_data"


SYNTHETIC_CIFAR100_1M:
  experiment:
    num_iterations: 1

  dataset:
    name: "SYNTHETIC_CIFAR100_1M"
    num_classes: 100
    image_size: 32
    for_extrapolation:
      value: true
      subset_size: 200000

  model:
    name: "ResNet50"

  training:
    batch_size: 256
    num_epochs: 50
    lr: 0.001
    weight_decay: 0.001

  uncertainty:
    window: 10

  pruning:
    prune: false
    percentages: [0.1, 0.2, 0.5]

  logging:
    log_interval: 15000

  paths:
    scores: "/nfs/homedirs/dhp/unsupervised-data-pruning/scores/extrapolation/subset"
    models: "/nfs/homedirs/dhp/unsupervised-data-pruning/models/SYNTHETIC_CIFAR100_1M/subset_data"

places365:
  experiment:
    num_iterations: 1

  dataset:
    name: "PLACES_365"
    num_classes: 365
    image_size: 64
    for_extrapolation:
      value: false
      subset_size: 450000

  model:
    name: "ResNet50"

  training:
    batch_size: 128
    num_epochs: 50
    lr: 0.001
    weight_decay: 0.001

  uncertainty:
    window: 10

  pruning:
    prune: false
    percentages: [0.1, 0.2, 0.5]

  logging:
    log_interval: 15000

  paths:
    scores: "/nfs/homedirs/dhp/unsupervised-data-pruning/scores/prune"
    models: "/nfs/homedirs/dhp/unsupervised-data-pruning/models/places365/full_data"
