SYNTHETIC_CIFAR100_1M:
  experiment:
    num_iterations: 1

  dataset:
    name: "CIFAR10"
    num_classes: 10
    image_size: 32

  training:
    batch_size: 256
    num_epochs: 50
    lr: 0.001
    weight_decay: 0.001

  pruning:
    percentages: [0.8, 0.9, 0.95]

  logging:
    log_interval: 15000

  json_path: "/nfs/homedirs/dhp/unsupervised-data-pruning/scores/extrapolation/extrapolated/knn_extrapolation_PLACES_365_resnet50-self-trained_k_50_seed_450000_euclidean.json"
  wandb_name: "knn-extrapolation"

PLACES_365:
  experiment:
    num_iterations: 1

  dataset:
    name: "PLACES_365"
    num_classes: 365
    image_size: 64

  model:
    name: "ResNet50"

  training:
    batch_size: 128
    num_epochs: 50
    lr: 0.001
    weight_decay: 0.001

  pruning:
    percentages: [0.1, 0.2, 0.5]

  logging:
    log_interval: 15000

  json_path: "/nfs/homedirs/dhp/unsupervised-data-pruning/scores/extrapolation/extrapolated/knn_extrapolation_PLACES_365_resnet50-self-trained_k_50_seed_450000_euclidean.json"
  wandb_name: "knn-extrapolation"