SYNTHETIC_CIFAR100_1M:
  experiment:
    num_iterations: 1

  dataset:
    name: "SYNTHETIC_CIFAR100_1M"
    num_classes: 100
    image_size: 32

  model:
    name: "ResNet50"

  training:
    batch_size: 256
    num_epochs: 50
    lr: 0.001
    weight_decay: 0.001

  pruning:
    percentages: [0.95, 0.9, 0.8, 0.5, 0.2, 0.1]

  logging:
    log_interval: 15000

  json_path: "/nfs/homedirs/dhp/unsupervised-data-pruning/scores/extrapolation/extrapolated/knn_tdds_SYNTHETIC_CIFAR100_1M_avg_resnet50-self-trained_k_50_seed_200000_euclidean.json"
  wandb_name: "knn-tdds-k-50-seed-200000-"

PLACES_365:
  experiment:
    num_iterations: 1

  dataset:
    name: "PLACES_365"
    num_classes: 365
    image_size: 64

  model:
    name: "ResNet50"

  training:
    batch_size: 128
    num_epochs: 50
    lr: 0.001
    weight_decay: 0.001

  pruning:
    percentages: [0.9, 0.95, 0.8, 0.5]

  logging:
    log_interval: 15000

  json_path: "/nfs/homedirs/dhp/unsupervised-data-pruning/scores/extrapolation/extrapolated/gnn_extrapolation_DU_PLACES_365_resnet50-self-trained_k_10_seed_450000_euclidean.json"
  wandb_name: "gnn-DU-k-10-seed-450000-"