SYNTHETIC_CIFAR100_1M:
  experiment:
    num_iterations: 1

  dataset:
    name: "SYNTHETIC_CIFAR100_1M"
    num_classes: 100
    image_size: 32

  model:
    name: "ResNet50"

  training:
    batch_size: 256
    num_epochs: 50
    lr: 0.001
    weight_decay: 0.001

  pruning:
    percentages: [0.5, 0.8, 0.9, 0.95]

  logging:
    log_interval: 15000


PLACES_365:
  experiment:
    num_iterations: 1

  dataset:
    name: "PLACES_365"
    num_classes: 365
    image_size: 64

  model:
    name: "ResNet50"

  training:
    batch_size: 128
    num_epochs: 50
    lr: 0.001
    weight_decay: 0.001

  pruning:
    percentages: [0, 0.1, 0.2, 0.5]

  logging:
    log_interval: 15000


IMAGENET:
  experiment:
    num_iterations: 3

  dataset:
    name: "IMAGENET"
    num_classes: 1000
    image_size: 64

  model:
    name: "ResNet18"

  training:
    batch_size: 256
    num_epochs: 90
    lr: 0.001
    weight_decay: 0.0001

  pruning:
    percentages: [0, 0.1, 0.2, 0.5, 0.8, 0.9, 0.95]

  logging:
    log_interval: 45000
