CIFAR10:
  experiment:
    num_iterations: 2

  dataset:
    name: "CIFAR10"
    num_classes: 10
    image_size: 32

  model:
    name: "ResNet18"

  pruning:
    # prune: false
    prune: true
    percentages: [0.95, 0.9, 0.8, 0.5, 0.2, 0.1]

  training:
    batch_size: 256
    num_epochs: 50
    lr: 0.001
    weight_decay: 0.001

  zcoreset:
    embedding: ["resnet18", "clip"]
    # embedding: ["resnet18"]
    n_sample: 1000000
    sample_dim: 2
    num_workers: 10
    rand_init: true
    redund_nn: 1000
    redund_exp: 4
    trial: 1

  logging:
    log_interval: 15000

  paths:
    scores: "/nfs/homedirs/dhp/unsupervised-data-pruning/scores/prune"


SYNTHETIC_CIFAR100_1M:
  experiment:
    num_iterations: 3

  dataset:
    name: "SYNTHETIC_CIFAR100_1M"
    num_classes: 100
    image_size: 32

  model:
    name: "ResNet50"

  training:
    batch_size: 256
    num_epochs: 50
    lr: 0.001
    weight_decay: 0.001

  zcoreset:
    embedding: ["resnet18", "clip"]
    # embedding: ["resnet18"]
    n_sample: 1000000
    sample_dim: 2
    num_workers: 10
    rand_init: true
    redund_nn: 1000
    redund_exp: 4
    trial: 1

  pruning:
    prune: true
    percentages: [0.1, 0.2, 0.5, 0.8, 0.9, 0.95]

  logging:
    log_interval: 15000

  paths:
    scores: "/nfs/homedirs/dhp/unsupervised-data-pruning/scores/prune"

PLACES_365:
  experiment:
    num_iterations: 3

  dataset:
    name: "PLACES_365"
    num_classes: 365
    image_size: 64

  model:
    name: "ResNet50"

  training:
    batch_size: 128
    num_epochs: 50
    lr: 0.001
    weight_decay: 0.001

  zcoreset:
    embedding: ["resnet18", "clip"]
    # embedding: ["resnet18"]
    n_sample: 1000000
    sample_dim: 2
    num_workers: 10
    rand_init: true
    redund_nn: 1000
    redund_exp: 4
    trial: 1

  pruning:
    prune: true
    percentages: [0.1, 0.2, 0.5, 0.8, 0.9, 0.95]

  logging:
    log_interval: 15000

  paths:
    scores: "/nfs/homedirs/dhp/unsupervised-data-pruning/scores/prune"

IMAGENET:
  experiment:
    num_iterations: 1

  dataset:
    name: "IMAGENET"
    num_classes: 1000
    image_size: 64

  model:
    name: "ResNet18"

  training:
    batch_size: 256
    num_epochs: 90
    lr: 0.001
    weight_decay: 0.0001

  zcoreset:
    embedding: ["resnet18", "clip"]
    # embedding: ["resnet18"]
    n_sample: 1000000
    sample_dim: 2
    num_workers: 10
    rand_init: true
    redund_nn: 1000
    redund_exp: 4
    trial: 1

  pruning:
    prune: true
    percentages: [0.1, 0.2, 0.5, 0.8, 0.9, 0.95]

  logging:
    log_interval: 45000

  paths:
    scores: "/nfs/homedirs/dhp/unsupervised-data-pruning/scores/prune"
